[[services]]
name = "fast-api"
source = "."
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers $WORKERS --timeout-keep-alive $TIMEOUT --proxy-headers --forwarded-allow-ips '*'"

# Remove PORT, WORKERS, and TIMEOUT from [services.variables] 
# as you'll define them in the Railway UI.

[[plugins]]
name = "mongodb"