export const widgetThemePresets = {
  
  "lermoCustom": {
    main_title: "LERMO Asistent",
    
    // Light Mode Colors
    primary_color_light: "#E01E26", // Red based on LERMO logo
    secondary_color_light: "#B61319", // Darker red
    background_color_light: "#FFFFFF", // White, matching site background
    text_color_light: "#333333", // Dark gray for readable text
    button_text_color_light: "#FFFFFF", // White text on buttons
    button_bg_color_light: "#E01E26", // Red buttons
    header_bg_color_light: "#E01E26", // Red header
    header_text_color_light: "#FFFFFF", // White text on header
    icon_background_color_light: "#B61319", // Darker red for icons
    mode_toggle_background_light: "#E01E26", // Red for toggle
    emoji_bg_color_light: "#FFFFFF", // White for emoji backgrounds

    // Dark Mode Colors
    primary_color_dark: "#E01E26", // Red for consistency
    secondary_color_dark: "#FF4C52", // Lighter red for dark mode
    background_color_dark: "#222222", // Dark gray, similar to the dark sections
    text_color_dark: "#F5F5F5", // Off-white for readability
    button_text_color_dark: "#FFFFFF", // White text on buttons
    button_bg_color_dark: "#E01E26", // Red buttons
    header_bg_color_dark: "#B61319", // Darker red header
    header_text_color_dark: "#FFFFFF", // White text on header
    icon_background_color_dark: "#FF4C52", // Lighter red for dark mode icons
    mode_toggle_background_dark: "#B61319", // Darker red for toggle
    emoji_bg_color_dark: "#333333", // Dark gray for emoji backgrounds

    font_family: 'Inter, sans-serif',
    greeting_message: "Hello! Welcome to our modern support chat.",
    widget_button_text: "Chat Now",
    widget_help_text: "Get instant help",
    widget_padding: '1.25rem',
    message_spacing: '0.75rem',
    input_field_padding: '0.625rem',
    base_font_size: '1rem',
    header_font_weight: '700',
    message_font_weight: '400',
    button_font_weight: '600',
    widget_border_radius: '1.6rem',
    widget_border_style: 'solid',
    widget_border_width: '1px',
    message_bubble_border_radius: '1.2rem',
    message_bubble_border_style: 'none',
    message_bubble_border_width: '0px',
    input_field_border_radius: '0.8rem',
    input_field_border_style: 'solid',
    input_field_border_width: '1px',
    button_border_radius: '0.8rem',
    button_border_style: 'none',
    button_border_width: '0px',
    widget_shadow: '0 5px 15px rgba(224, 30, 38, 0.15)', // Subtle shadow with red tint
    custom_css: '',
  },
    "modern": {
      main_title: "Modern Chat",
      // Light Mode Colors
      primary_color_light: "#A61FF5",
      secondary_color_light: "#C564FA",
      background_color_light: "#F7F7FA",
      text_color_light: "#0F172A",
      button_text_color_light: "#FFFFFF",
      button_bg_color_light: "#A61FF5",
      header_bg_color_light: "#A61FF5",
      header_text_color_light: "#FFFFFF",
      icon_background_color_light: "#C564FA",
      mode_toggle_background_light: "#A61FF5",
      emoji_bg_color_light: "#FFFFFF",
  
      // Dark Mode Colors
      primary_color_dark: "#C564FA", // Lighter purple for visibility
      secondary_color_dark: "#A61FF5", // Original purple
      background_color_dark: "#1A1A2E", // Dark, almost-black gray
      text_color_dark: "#E0E0E0", // Light gray for readability
      button_text_color_dark: "#FFFFFF", // White text on buttons
      button_bg_color_dark: "#A61FF5", // Same purple as light mode
      header_bg_color_dark: "#A61FF5", // Same purple, consistent header
      header_text_color_dark: "#FFFFFF", // White header text
      icon_background_color_dark: "#C564FA",//complementary color
      mode_toggle_background_dark: "#A61FF5",//same as light mode.
      emoji_bg_color_dark: "#2C2C48", // Slightly lighter dark gray for emoji
  
      font_family: 'Inter, sans-serif',
      greeting_message: "Hello! Welcome to our modern support chat.",
      widget_button_text: "Chat Now",
      widget_help_text: "Get instant help",
      widget_padding: '1.25rem',
      message_spacing: '0.75rem',
      input_field_padding: '0.625rem',
      base_font_size: '1rem',
      header_font_weight: '700',
      message_font_weight: '400',
      button_font_weight: '600',
      widget_border_radius: '1.6rem',
      widget_border_style: 'solid',
      widget_border_width: '1px',
      message_bubble_border_radius: '1.2rem',
      message_bubble_border_style: 'none',
      message_bubble_border_width: '0px',
      input_field_border_radius: '0.8rem',
      input_field_border_style: 'solid',
      input_field_border_width: '1px',
      button_border_radius: '0.8rem',
      button_border_style: 'none',
      button_border_width: '0px',
      widget_shadow: '0 5px 15px rgba(14, 165, 233, 0.15)',
      custom_css: '',
    },
  
    "purpleModern": {
    main_title: "Modern Chat",

    // Primary Palette (Purple Scheme)
    primary_color_light: "#6A1B9A",   // Dark Purple
    secondary_color_light: "#9575CD", // Lavender
    background_color_light: "#F0F9FF", // Very Light Blue (like in the image)
    text_color_light: "#333333",       // Very Dark Gray
    button_text_color_light: "#FFFFFF", // White
    button_bg_color_light: "#9575CD",   // Lavender
    header_bg_color_light: "#6A1B9A",   // Dark Purple
    header_text_color_light: "#FFFFFF", // White
    icon_background_color_light: "#FFFFFF",
    mode_toggle_background_light: "#6A1B9A",
    emoji_bg_color_light: "#FFFFFF",

    // Dark Mode - Inverted
    primary_color_dark: "#9575CD",    // Lavender
    secondary_color_dark: "#6A1B9A",  // Dark Purple
    background_color_dark: "#121212",  // Very Dark Gray
    text_color_dark: "#EEEEEE",        // Light Gray
    button_text_color_dark: "#FFFFFF",  // White
    button_bg_color_dark: "#6A1B9A",    // Dark Purple
    header_bg_color_dark: "#9575CD",     // Lavender
    header_text_color_dark: "#FFFFFF",  // White
    icon_background_color_dark: "#6A1B9A",
    mode_toggle_background_dark: "#9575CD",
    emoji_bg_color_dark: "#1E293B",
    font_family: 'Inter, sans-serif', // Or your preferred font
    greeting_message: "Hello! Welcome to our modern support chat.", // Customize
    widget_button_text: "Chat Now",   // Customize
    widget_help_text: "Get instant help", // Customize
    widget_padding: '0rem',
    message_spacing: '0.75rem',
    input_field_padding: '0.625rem',
    base_font_size: '1rem',
    header_font_weight: '700',
    message_font_weight: '400',
    button_font_weight: '600',
    widget_border_radius: '1.6rem',
    widget_border_style: 'solid',
    widget_border_width: '0px',
    message_bubble_border_radius: '1.2rem',
    message_bubble_border_style: 'none',
    message_bubble_border_width: '0px',
    input_field_border_radius: '0.8rem',
    input_field_border_style: 'solid',
    input_field_border_width: '1px',
    button_border_radius: '0.8rem',
    button_border_style: 'none',
    button_border_width: '0px',
    widget_shadow: '0 5px 15px rgba(106, 27, 154, 0.2)', // Purple-toned shadow
    custom_css: '',
  },  
  
    "minimalist": {
      main_title: "Simple Support",
      // Light Mode Colors
      primary_color_light: "#4B5563",
      secondary_color_light: "#6B7280",
      background_color_light: "#FFFFFF",
      text_color_light: "#374151",
      button_text_color_light: "#FFFFFF",
      button_bg_color_light: "#6B7280",
      header_bg_color_light: "#F9FAFB",
      header_text_color_light: "#374151",
      icon_background_color_light: "#6B7280",
      mode_toggle_background_light: "#4B5563",
      emoji_bg_color_light: "#FFFFFF",
  
      // Dark Mode Colors
      primary_color_dark: "#D1D5DB",
      secondary_color_dark: "#9CA3AF",
      background_color_dark: "#1F2937",
      text_color_dark: "#E5E7EB",
      button_text_color_dark: "#FFFFFF",
      button_bg_color_dark: "#9CA3AF",
      header_bg_color_dark: "#1F2937",
      header_text_color_dark: "#E5E7EB",
      icon_background_color_dark: "#D1D5DB",
      mode_toggle_background_dark: "#9CA3AF",
      emoji_bg_color_dark: "#374151",
  
      font_family: 'Segoe UI, sans-serif',
      greeting_message: "Welcome! How can we help you today?",
      widget_button_text: "Need Help?",
      widget_help_text: "Chat with us",
      widget_padding: '1rem',
      message_spacing: '0.5rem',
      input_field_padding: '0.5rem',
      base_font_size: '0.9rem',
      header_font_weight: '700',
      message_font_weight: '400',
      button_font_weight: '500',
      widget_border_radius: '1.6rem',
      widget_border_style: 'solid',
      widget_border_width: '1px',
      message_bubble_border_radius: '0.8rem',
      message_bubble_border_style: 'none',
      message_bubble_border_width: '0px',
      input_field_border_radius: '0.6rem',
      input_field_border_style: 'solid',
      input_field_border_width: '1px',
      button_border_radius: '0.6rem',
      button_border_style: 'none',
      button_border_width: '0px',
      widget_shadow: 'none',
      custom_css: '',
    },
  
    "corporate": {
      main_title: "Enterprise Support",
      // Light Mode Colors
      primary_color_light: "#3B82F6",
      secondary_color_light: "#60A5FA",
      background_color_light: "#EFF6FF",
      text_color_light: "#1E293B",
      button_text_color_light: "#FFFFFF",
      button_bg_color_light: "#3B82F6",
      header_bg_color_light: "#3B82F6",
      header_text_color_light: "#FFFFFF",
      icon_background_color_light: "#60A5FA",
      mode_toggle_background_light: "#3B82F6",
      emoji_bg_color_light: "#FFFFFF",
  
      // Dark Mode Colors
      primary_color_dark: "#1D4ED8",
      secondary_color_dark: "#3B82F6",
      background_color_dark: "#1E293B",
      text_color_dark: "#CBD5E0",
      button_text_color_dark: "#FFFFFF",
      button_bg_color_dark: "#3B82F6",
      header_bg_color_dark: "#1D4ED8",
      header_text_color_dark: "#FFFFFF",
      icon_background_color_dark: "#3B82F6",
      mode_toggle_background_dark: "#1D4ED8",
      emoji_bg_color_dark: "#2C3A58",
  
      font_family: 'Montserrat, sans-serif',
      greeting_message: "Welcome to corporate support. How can we assist you?",
      widget_button_text: "Support Chat",
      widget_help_text: "Click to chat",
      widget_padding: '1.5rem',
      message_spacing: '0.625rem',
      input_field_padding: '0.75rem',
      base_font_size: '1.1rem',
      header_font_weight: '700',
      message_font_weight: '400',
      button_font_weight: '600',
      widget_border_radius: '1.6rem',
      widget_border_style: 'none',
      widget_border_width: '0px',
      message_bubble_border_radius: '1.2rem',
      message_bubble_border_style: 'none',
      message_bubble_border_width: '0px',
      input_field_border_radius: '0.8rem',
      input_field_border_style: 'solid',
      input_field_border_width: '1px',
      button_border_radius: '0.8rem',
      button_border_style: 'none',
      button_border_width: '0px',
      widget_shadow: '0 3px 7px rgba(59, 130, 246, 0.15)',
      custom_css: '',
    },
  
    "fun": {
      main_title: "Let's Chat!",
      // Light Mode Colors
      primary_color_light: "#EC4899",
      secondary_color_light: "#F472B6",
      background_color_light: "#FDF2F8",
      text_color_light: "#4A148C",
      button_text_color_light: "#FFFFFF",
      button_bg_color_light: "#EC4899",
      header_bg_color_light: "#EC4899",
      header_text_color_light: "#FFFFFF",
      icon_background_color_light: "#F472B6",
      mode_toggle_background_light: "#EC4899",
      emoji_bg_color_light: "#FFFFFF",
  
      // Dark Mode Colors
      primary_color_dark: "#DB2777",
      secondary_color_dark: "#EC4899",
      background_color_dark: "#4A044E",
      text_color_dark: "#FCE7F3",
      button_text_color_dark: "#FFFFFF",
      button_bg_color_dark: "#EC4899",
      header_bg_color_dark: "#DB2777",
      header_text_color_dark: "#FFFFFF",
      icon_background_color_dark: "#EC4899",
      mode_toggle_background_dark: "#DB2777",
      emoji_bg_color_dark: "#6D1B6B",
  
      font_family: 'Comic Neue, cursive',
      greeting_message: "Hey! Ready to have some fun chatting?",
      widget_button_text: "Talk to Us!",
      widget_help_text: "We're fun to chat with!",
      widget_padding: '1rem',
      message_spacing: '0.5rem',
      input_field_padding: '0.5rem',
      base_font_size: '1rem',
      header_font_weight: '700',
      message_font_weight: '400',
      button_font_weight: '700',
      widget_border_radius: '1.6rem',
      widget_border_style: 'dashed',
      widget_border_width: '2px',
      message_bubble_border_radius: '1.4rem',
      message_bubble_border_style: 'none',
      message_bubble_border_width: '0px',
      input_field_border_radius: '1rem',
      input_field_border_style: 'dashed',
      input_field_border_width: '2px',
      button_border_radius: '1rem',
      button_border_style: 'dashed',
      button_border_width: '2px',
      widget_shadow: '0 7px 10px rgba(236, 72, 153, 0.15)',
      custom_css: '',
    },
  
    "realestate": {
      main_title: "Property Chat",
      // Light Mode Colors
      primary_color_light: "#2563EB",
      secondary_color_light: "#3B82F6",
      background_color_light: "#E8F0FE",
      text_color_light: "#1E293B",
      button_text_color_light: "#FFFFFF",
      button_bg_color_light: "#3B82F6",
      header_bg_color_light: "#2563EB",
      header_text_color_light: "#FFFFFF",
      icon_background_color_light: "#3B82F6",
      mode_toggle_background_light: "#2563EB",
      emoji_bg_color_light: "#FFFFFF",
  
      // Dark Mode Colors
      primary_color_dark: "#1E40AF",
      secondary_color_dark: "#2563EB",
      background_color_dark: "#0F1A2F",
      text_color_dark: "#E2E8F0",
      button_text_color_dark: "#FFFFFF",
      button_bg_color_dark: "#2563EB",
      header_bg_color_dark: "#1E40AF",
      header_text_color_dark: "#FFFFFF",
      icon_background_color_dark: "#2563EB",
      mode_toggle_background_dark: "#1E40AF",
      emoji_bg_color_dark: "#1E293B",
  
      font_family: 'Poppins, sans-serif',
      greeting_message: "Looking for a new property? Let us help!",
      widget_button_text: "Explore Now",
      widget_help_text: "Chat about properties",
      widget_padding: '1.25rem',
      message_spacing: '0.75rem',
      input_field_padding: '0.625rem',
      base_font_size: '1rem',
      header_font_weight: '700',
      message_font_weight: '400',
      button_font_weight: '600',
      widget_border_radius: '1.6rem',
      widget_border_style: 'solid',
      widget_border_width: '1px',
      message_bubble_border_radius: '1.2rem',
      message_bubble_border_style: 'none',
      message_bubble_border_width: '0px',
      input_field_border_radius: '0.8rem',
      input_field_border_style: 'solid',
      input_field_border_width: '1px',
      button_border_radius: '0.8rem',
      button_border_style: 'none',
      button_border_width: '0px',
      widget_shadow: '0 5px 15px rgba(37, 99, 235, 0.1)',
      custom_css: '',
    },
  
    "health": {
      main_title: "Health Care",
      // Light Mode Colors
      primary_color_light: "#10B981",
      secondary_color_light: "#34D399",
      background_color_light: "#ECFDF5",
      text_color_light: "#065F46",
      button_text_color_light: "#FFFFFF",
      button_bg_color_light: "#10B981",
      header_bg_color_light: "#10B981",
      header_text_color_light: "#FFFFFF",
      icon_background_color_light: "#34D399",
      mode_toggle_background_light: "#10B981",
      emoji_bg_color_light: "#FFFFFF",
  
      // Dark Mode Colors
      primary_color_dark: "#059669",
      secondary_color_dark: "#10B981",
      background_color_dark: "#042F2E",
      text_color_dark: "#D1FAE5",
      button_text_color_dark: "#FFFFFF",
      button_bg_color_dark: "#059669",
      header_bg_color_dark: "#059669",
      header_text_color_dark: "#FFFFFF",
      icon_background_color_dark: "#10B981",
      mode_toggle_background_dark: "#059669",
      emoji_bg_color_dark: "#0D443C",
  
      font_family: 'Lato, sans-serif',
      greeting_message: "How can we support your health today?",
      widget_button_text: "Get Health Advice",
      widget_help_text: "Ask us anything",
      widget_padding: '1.25rem',
      message_spacing: '0.75rem',
      input_field_padding: '0.625rem',
      base_font_size: '1rem',
      header_font_weight: '700',
      message_font_weight: '400',
      button_font_weight: '600',
      widget_border_radius: '1.6rem',
      widget_border_style: 'solid',
      widget_border_width: '1px',
      message_bubble_border_radius: '1.2rem',
      message_bubble_border_style: 'none',
      message_bubble_border_width: '0px',
      input_field_border_radius: '0.8rem',
      input_field_border_style: 'solid',
      input_field_border_width: '1px',
      button_border_radius: '0.8rem',
      button_border_style: 'none',
      button_border_width: '0px',
      widget_shadow: '0 5px 15px rgba(16, 185, 129, 0.1)',
      custom_css: '',
    },
  
    "finance": {
      main_title: "Financial Advice",
      // Light Mode Colors
      primary_color_light: "#6366F1",
      secondary_color_light: "#818CF8",
      background_color_light: "#EEF2FF",
      text_color_light: "#3730A3",
      button_text_color_light: "#FFFFFF",
      button_bg_color_light: "#6366F1",
      header_bg_color_light: "#6366F1",
      header_text_color_light: "#FFFFFF",
      icon_background_color_light: "#818CF8",
      mode_toggle_background_light: "#6366F1",
      emoji_bg_color_light: "#FFFFFF",
  
      // Dark Mode Colors
      primary_color_dark: "#4F46E5",
      secondary_color_dark: "#6366F1",
      background_color_dark: "#1E1B4B",
      text_color_dark: "#E0E7FF",
      button_text_color_dark: "#FFFFFF",
      button_bg_color_dark: "#4F46E5",
      header_bg_color_dark: "#4F46E5",
      header_text_color_dark: "#FFFFFF",
      icon_background_color_dark: "#6366F1",
      mode_toggle_background_dark: "#4F46E5",
      emoji_bg_color_dark: "#2E2A66",
  
      font_family: 'Roboto Condensed, sans-serif',
      greeting_message: "Need financial guidance? We're here to help!",
      widget_button_text: "Get Advice",
      widget_help_text: "Financial assistance",
      widget_padding: '1.25rem',
      message_spacing: '0.75rem',
      input_field_padding: '0.625rem',
      base_font_size: '1rem',
      header_font_weight: '700',
      message_font_weight: '400',
      button_font_weight: '600',
      widget_border_radius: '1.6rem',
      widget_border_style: 'solid',
      widget_border_width: '1px',
      message_bubble_border_radius: '1.2rem',
      message_bubble_border_style: 'none',
      message_bubble_border_width: '0px',
      input_field_border_radius: '0.8rem',
      input_field_border_style: 'solid',
      input_field_border_width: '1px',
      button_border_radius: '0.8rem',
      button_border_style: 'none',
      button_border_width: '0px',
      widget_shadow: '0 5px 15px rgba(99, 102, 241, 0.1)',
      custom_css: '',
    },
  "ecommerce": {
    main_title: "Shop Assistance",
    // Light Mode Colors
    primary_color_light: "#F59E0B",
    secondary_color_light: "#FACC15",
    background_color_light: "#FFFBEB",
    text_color_light: "#78350F",
    button_text_color_light: "#78350F",
    button_bg_color_light: "#FACC15",
    header_bg_color_light: "#F59E0B",
    header_text_color_light: "#78350F",
    icon_background_color_light: "#FACC15",
    mode_toggle_background_light: "#F59E0B",
    emoji_bg_color_light: "#FFFFFF",
  
    // Dark Mode Colors
    primary_color_dark: "#D97706",
    secondary_color_dark: "#EAB308",
    background_color_dark: "#432818",
    text_color_dark: "#FEF3C7",
    button_text_color_dark: "#FFFFFF",
    button_bg_color_dark: "#D97706",
    header_bg_color_dark: "#D97706",
    header_text_color_dark: "#FFFFFF",
    icon_background_color_dark: "#EAB308",
    mode_toggle_background_dark: "#D97706",
    emoji_bg_color_dark: "#6B4226",
  
    font_family: 'Open Sans, sans-serif',
    greeting_message: "Welcome! How can we help you shop today?",
    widget_button_text: "Shop Now",
    widget_help_text: "Find what you need",
    widget_padding: '1.25rem',
    message_spacing: '0.75rem',
    input_field_padding: '0.625rem',
    base_font_size: '1rem',
    header_font_weight: '700',
    message_font_weight: '400',
    button_font_weight: '600',
    widget_border_radius: '1.6rem',
    widget_border_style: 'solid',
    widget_border_width: '1px',
    message_bubble_border_radius: '1.2rem',
    message_bubble_border_style: 'none',
    message_bubble_border_width: '0px',
    input_field_border_radius: '0.8rem',
    input_field_border_style: 'solid',
    input_field_border_width: '1px',
    button_border_radius: '0.8rem',
    button_border_style: 'none',
    button_border_width: '0px',
    widget_shadow: '0 5px 15px rgba(245, 158, 11, 0.1)',
    custom_css: '',
  },
  
  "education": {
    main_title: "Learning Support",
    // Light Mode Colors
    primary_color_light: "#22D3EE",
    secondary_color_light: "#67E8F9",
    background_color_light: "#F0FDFA",
    text_color_light: "#064E3B",
    button_text_color_light: "#FFFFFF",
    button_bg_color_light: "#22D3EE",
    header_bg_color_light: "#22D3EE",
    header_text_color_light: "#FFFFFF",
    icon_background_color_light: "#67E8F9",
    mode_toggle_background_light: "#22D3EE",
    emoji_bg_color_light: "#FFFFFF",
  
    // Dark Mode Colors
    primary_color_dark: "#06B6D4",
    secondary_color_dark: "#22D3EE",
    background_color_dark: "#063B49",
    text_color_dark: "#C7F9FA",
    button_text_color_dark: "#FFFFFF",
    button_bg_color_dark: "#06B6D4",
    header_bg_color_dark: "#06B6D4",
    header_text_color_dark: "#FFFFFF",
    icon_background_color_dark: "#22D3EE",
    mode_toggle_background_dark: "#06B6D4",
    emoji_bg_color_dark: "#0D4F62",
  
    font_family: 'Nunito, sans-serif',
    greeting_message: "Welcome to our learning platform! How can we assist you?",
    widget_button_text: "Learn More",
    widget_help_text: "Ask us anything",
    widget_padding: '1.25rem',
    message_spacing: '0.75rem',
    input_field_padding: '0.625rem',
    base_font_size: '1rem',
    header_font_weight: '700',
    message_font_weight: '400',
    button_font_weight: '600',
    widget_border_radius: '1.6rem',
    widget_border_style: 'solid',
    widget_border_width: '1px',
    message_bubble_border_radius: '1.2rem',
    message_bubble_border_style: 'none',
    message_bubble_border_width: '0px',
    input_field_border_radius: '0.8rem',
    input_field_border_style: 'solid',
    input_field_border_width: '1px',
    button_border_radius: '0.8rem',
    button_border_style: 'none',
    button_border_width: '0px',
    widget_shadow: '0 5px 15px rgba(34, 211, 238, 0.1)',
    custom_css: '',
  },
  
  "travel": {
    main_title: "Travel Assistance",
    // Light Mode Colors
    primary_color_light: "#EA580C",
    secondary_color_light: "#F97316",
    background_color_light: "#FFEDD5",
    text_color_light: "#7C2D12",
    button_text_color_light: "#FFFFFF",
    button_bg_color_light: "#F97316",
    header_bg_color_light: "#EA580C",
    header_text_color_light: "#FFFFFF",
    icon_background_color_light: "#F97316",
    mode_toggle_background_light: "#EA580C",
    emoji_bg_color_light: "#FFFFFF",
  
    // Dark Mode Colors
    primary_color_dark: "#C2410C",
    secondary_color_dark: "#EA580C",
    background_color_dark: "#431407",
    text_color_dark: "#FFE4C4",
    button_text_color_dark: "#FFFFFF",
    button_bg_color_dark: "#C2410C",
    header_bg_color_dark: "#C2410C",
    header_text_color_dark: "#FFFFFF",
    icon_background_color_dark: "#EA580C",
    mode_toggle_background_dark: "#C2410C",
    emoji_bg_color_dark: "#69230D",
  
    font_family: 'Raleway, sans-serif',
    greeting_message: "Planning your next adventure? Let us help!",
    widget_button_text: "Explore Destinations",
    widget_help_text: "Chat with a travel expert",
    widget_padding: '1.25rem',
    message_spacing: '0.75rem',
    input_field_padding: '0.625rem',
    base_font_size: '1rem',
    header_font_weight: '700',
    message_font_weight: '400',
    button_font_weight: '600',
    widget_border_radius: '1.6rem',
    widget_border_style: 'solid',
    widget_border_width: '1px',
    message_bubble_border_radius: '1.2rem',
    message_bubble_border_style: 'none',
    message_bubble_border_width: '0px',
    input_field_border_radius: '0.8rem',
    input_field_border_style: 'solid',
    input_field_border_width: '1px',
    button_border_radius: '0.8rem',
    button_border_style: 'none',
    button_border_width: '0px',
    widget_shadow: '0 5px 15px rgba(234, 88, 12, 0.1)',
    custom_css: '',
  },
  "startup": {
    main_title: "Startup Support",
    // Light Mode Colors
    primary_color_light: "#A855F7",
    secondary_color_light: "#C084FC",
    background_color_light: "#F5F3FF",
    text_color_light: "#4C1D95",
    button_text_color_light: "#FFFFFF",
    button_bg_color_light: "#A855F7",
    header_bg_color_light: "#A855F7",
    header_text_color_light: "#FFFFFF",
    icon_background_color_light: "#C084FC",
    mode_toggle_background_light: "#A855F7",
    emoji_bg_color_light: "#FFFFFF",
  
    // Dark Mode Colors
    primary_color_dark: "#7E22CE",
    secondary_color_dark: "#9333EA",
    background_color_dark: "#2E1065",
    text_color_dark: "#E9D5FF",
    button_text_color_dark: "#FFFFFF",
    button_bg_color_dark: "#7E22CE",
    header_bg_color_dark: "#7E22CE",
    header_text_color_dark: "#FFFFFF",
    icon_background_color_dark: "#9333EA",
    mode_toggle_background_dark: "#7E22CE",
    emoji_bg_color_dark: "#4A2185",
  
    font_family: 'IBM Plex Sans, sans-serif',
    greeting_message: "Welcome! How can we help your startup grow?",
    widget_button_text: "Get Started",
    widget_help_text: "We're here to assist",
    widget_padding: '1.25rem',
    message_spacing: '0.75rem',
    input_field_padding: '0.625rem',
    base_font_size: '1rem',
    header_font_weight: '700',
    message_font_weight: '400',
    button_font_weight: '600',
    widget_border_radius: '1.6rem',
    widget_border_style: 'solid',
    widget_border_width: '1px',
    message_bubble_border_radius: '1.2rem',
    message_bubble_border_style: 'none',
    message_bubble_border_width: '0px',
    input_field_border_radius: '0.8rem',
    input_field_border_style: 'solid',
    input_field_border_width: '1px',
    button_border_radius: '0.8rem',
    button_border_style: 'none',
    button_border_width: '0px',
    widget_shadow: '0 5px 15px rgba(168, 85, 247, 0.1)',
    custom_css: '',
  },
  };